#!/bin/bash --login
#PBS -N MONC
#PBS -l select=1
#PBS -l walltime=12:00:00
#PBS -j oe
#q short

#export MPICH_MAX_THREAD_SAFETY=multiple

# Set the number of threads to 1
#   This prevents any system libraries from automatically  
#   using threading.
#export OMP_NUM_THREADS=1
module load python-compute/2.7.6
module load pc-netcdf4-python
module load pc-numpy
module load pc-scipy

cd /work/n02/n02/sboeing/MONC_pp
#aprun -n 1 -d 24 python test.py
aprun -n 1 -d 24 python pp_MONC.py -c bubble_500.cfg -s archer.syscfg warm_pert_2017 000 --overwrite
